### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by DrHenchman** [DrHenchman/uhc-pack#25]
It would be great to get to the point where I'm happy to consider the datapack 1.0. Although the datapack has been stable for quite some time, there have been some missing features and bugfixes which I want to get done before then

Roadmap:

- [x] Fix the pre-generation done vs total #29 
- [x] Clean up the book to be neater #18 
- [x] Clean up documentation
- [x] Make discord server public #28 
- [ ] Include documentation for all features #19 
- [ ] Add pack.png icon #38 
- [x] Verify the datapack works correctly on Paper #55
- [x] Include screenshots in the documentation
- [ ] Create a YouTube showcase video
- [x] ~~Create github.io website?~~
- [ ] Add option to allow for chance of salvage to drop when mining stone #70 
- [ ] Add option to avoid stone variants dropping #69
- [ ] Add option to enable auto-smelting of ore #68
- [ ] 1.17 support #51
